dist: xenial   # required for Python >= 3.7
sudo: true
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  # Export ALIGNAKAPP_APP_DIR, only needed for Travis.
  - export ALIGNAKAPP_APP_DIR=$HOME/.local/alignak_app
  - export ALIGNAKAPP_USR_DIR=$HOME/.local/alignak_app
  - export ALIGNAKAPP_LOG_DIR=$HOME/.local/alignak_app

script: cd ./tests/ && python3 -m coverage run test.py
