--- 
addons: 
  apt: 
    packages: 
      - libxkbcommon-x11-0
      - python3-pyqt5
before_script: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
dist: xenial
language: python
python: 
  - "3.5"
  - "3.6"
  - "3.7"
script: "xvfb-run cd ./tests/ && python3 -m coverage run test.py"
services: 
  - xvfb
sudo: true
