--- 
addons: 
  apt: 
    packages: 
      - libxkbcommon-x11-0
      - python3-pyqt5
dist: xenial
language: python
python: 
  - "3.5"
  - "3.6"
  - "3.7"
script: "xvfb-run -a python3 -m coverage run tests/test.py"
services: 
  - xvfb
sudo: true
