dist: xenial   # required for Python >= 3.7
addons:
  apt:
    packages:
    - libxkbcommon-x11-0
sudo: true
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_script:
  - sudo apt-get install -qq libegl1-mesa
script: cd ./tests/ && python3 -m coverage run test.py
